#!/usr/bin/env bash

BASE_DIR=$(dirname $0)

if [[ "install" == $1 ]]; then
    echo "Installing dot configuration files"
    cp -v ${BASE_DIR}/vimrc ${HOME}/.vimrc
    
    echo "Installing Vundle"
    rm -rf ${HOME}/.vim/bundle/Vundle.vim
    git clone https://github.com/VundleVim/Vundle.vim.git ${HOME}/.vim/bundle/Vundle.vim

    if [[ ! -a "/bin/zsh" ]]; then
        echo "Install zsh first"
    else
        echo "Installing Oh-my-zsh"
        cp -v ${BASE_DIR}/zshrc ${HOME}/.zshrc
        rm -rf ${HOME}/.oh-my-zsh
        git clone https://github.com/ohmyzsh/ohmyzsh.git ${HOME}/.oh-my-zsh
        git clone https://github.com/zsh-users/zsh-syntax-highlighting.git \
            ${HOME}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
        echo "Installing aliases"
        cp -v ${BASE_DIR}/aliases ${HOME}/.oh-my-zsh/custom/aliases.zsh
    fi

    echo "Then you should:"
    echo "1) open vim and run :PluginInstall"
    echo "2) source ~/.zshrc"
    
elif [[ "minimal" == $1 ]]; then
    echo "Minimal installing dot configuration files"
    cp -v ${BASE_DIR}/minimal/vimrc ${HOME}/.vimrc

elif [[ "uninstall" == $1 ]]; then
    echo "Uninstalling dot configuration files"
    rm ${HOME}/.vimrc

    echo "Uninstalling Vundle"
    rm -rf ${HOME}/.vim/bundle/Vundle.vim

    if [[ -a "${HOME}/.zshrc" ]]; then
        echo "Uninstalling oh-my-zsh and config files"
        rm ${HOME}/.zshrc
        rm -rf ${HOME}/.oh-my-zsh
    fi

else
    echo "Usage: config install/uninstall"
fi
